version: '3.8'
#la versione non so quale mettere per ora lascio questa
services:
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache-cli --host 0.0.0.0 --port 8080 --accounts 10 --defaultBalanceEther 1000 --mnemonic "saddle point immune salmon swear indoor riot process easily marine charge leave"
    #qui specifica i paramentri in esecuzione su ganache                    in particolare crea 10 account e imposta il saldo a 1000 ether infine utilizza questa frase mnemonica per generare gli account
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 10s
      retries: 5
#tutto quello qua sopra può essere cambiato in base a quello che vogliamo ma non so bene tipo le cose delle porte, cercare
#questa sotto è la seconda immagine che dipende da ganache



  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: loris
      MYSQL_DATABASE: healthchain
      #MYSQL_USER: root
      #MYSQL_PASSWORD: loris
    ports:
      - 8081:8081
    volumes:
      - db_data:/var/lib/mysql

  healthchain:
    build: .
    stdin_open: true
    tty: true
    #queste due istruzioni attivano l'interfaccia interattiva da terminale. non so se ci servono, non so neanche se serve dockerizzare XDXD
    depends_on:
      - ganache
      - db
    restart: always
    environment:
      - DISPLAY=host.docker.internal:0
      - ETHEREUM_NODE_URL=http://ganache:8080
    #se decidiamo di cambiare la porta dobbiamo cambiare anche qui
    ports:
      - 3000:3000

volumes:
  db_data:
    driver: local